# Generated by Django 3.0.7 on 2020-06-19 23:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(help_text='Name of the item, ie.Barbaque Beef', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short Item description ie. Short ribs, olive oil, caraway seeds, yoghurt, carrots, onions, white cabbage ', max_length=140)),
                ('price', models.IntegerField(help_text='Item price ie. 700')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='account.RestaurantProfile')),
            ],
            options={
                'ordering': ('created',),
                'unique_together': {('name', 'restaurant')},
            },
        ),
    ]
