# Generated by Django 3.0.7 on 2020-06-20 00:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('restaurant', '0002_menu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableReserve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('no_of_seats', models.IntegerField(help_text='No of seats.')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='account.ClientProfile')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='account.RestaurantProfile')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
